version: '3.8'

services:
  backend:
    build: .
    container_name: ai-voice-assistant
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - model-cache:/root/.cache
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  model-cache:
